version: "3.8"
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-vector
    ports:
      - "6379:6379"
      - "8801:8801" # RedisInsight UI
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  redis_data:
